### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by violetymr** [wenhuchen/KGPT#2]
Hi, when I try to run the "run.py", I get the following error.
Segmentation fault (core dumped)
both the Sequence Encoder and Graph Encoder

Anyone have a solution to this error please let me know

**Comment by wenhuchen** [comment]
Could you give me more information? I think it's most likely due to the wrong python library you used. Can you use the dependency library version I specified in the github.

**Comment by violetymr** [comment]
Thanks a lot for your reply! I've checked the library version, it seems right. Maybe I think the error is due to Out of memory? Cause when I try to load weight from DialoGPT-small, the same problem occurs.

The version is as follows:
`torch                     1.4.0                     <pip>
tqdm                      4.51.0                    <pip>
transformers              2.6.0                     <pip>`

The error message is as follows:
`scripts/e2enlg/finetune_sequence_e2enlg_from_wikidata.sh: line 8: 32768 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES=${GPUS} python code/run.py --batch_size 32 --dataset e2enlg --tokenizer_dir ${FOLDER}/GPT2_tokenizer/ --max_enc_len 256 --max_dec_len 72 --num_workers 8 --epochs 30 --printing_steps 200 --save_every_n_epochs 2 --learning_rate 2e-5 --finetune --encoder sequence --load_from ${RESUME}`

**Comment by wenhuchen** [comment]
I don't see a lot of useful information here, it might not be related to my code at all. Maybe you can first solve the OOM problem and see it helps.
