### ISSUE TITLE
KeyError: 'module.embedding.word_embeddings.weight'

### ISSUE THREAD

**Issue by lKingslayer** [wenhuchen/KGPT#3]
When I tried to run:
`bash scripts/webnlg/finetune_graph_e2enlg_from_wikidata.sh 0 checkpoint_wikidata/checkpoint_sequence_head8_layer6_GPT2_maxfact12/model_ep14.pt` 

It gave me the following error.
`Traceback (most recent call last):
  File "code/run.py", line 176, in <module>
    load_my_state_dict(model, reloaded)
  File "code/run.py", line 82, in load_my_state_dict
    own_state[name].copy_(param)
KeyError: 'module.embedding.word_embeddings.weight'`

Do you know why this error happens, thanks!

**Comment by wenhuchen** [comment]
It seems that you have a typo "scripts/webnlg/finetune_graph_e2enlg_from_wikidata.sh", the folder is webnlg, the script is for e2enlg. It's misaligned.

**Comment by lKingslayer** [comment]
Yeah, sorry, there was a typo. It should be 
`bash scripts/webnlg/finetune_graph_e2enlg_from_wikidata.sh 0 checkpoint_wikidata/checkpoint_sequence_head8_layer6_GPT2_maxfact12/model_ep14.pt`. And I still get this error.

**Comment by lKingslayer** [comment]
Yeah, sorry, there was a typo. It should be 
`bash scripts/webnlg/finetune_graph_webnlg_from_wikidata.sh 0 checkpoint_wikidata/checkpoint_sequence_head8_layer6_GPT2_maxfact12/model_ep14.pt`
And I still get this error.

**Comment by lKingslayer** [comment]
I have solved the error. Thank you!
