### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'GraphGatedTransformerDecoder' object has no attribute 'beam_search'     │

### ISSUE THREAD

**Issue by lKingslayer** [wenhuchen/KGPT#4]
Hi, I have a problem when I am trying to evaluate all the fine-tuned models using graph encoder. It gives me the following errors:
`torch.nn.modules.module.ModuleAttributeError: 'GraphGatedTransformerDecoder' object has no attribute 'beam_search'     │`
And then I inspect the Model.py, I find out that there is indeed no 'beam_search' under 'GraphGatedTransformerDecoder'. But  I see that in all the eval_graph_*_all.sh files, you set the '--beam_size 2' which means that it is using beam_search. I am really confused about this. Thanks!

**Comment by wenhuchen** [comment]
Hi, sorry for the confusion. For the graph transformer, I actually used greedy decoding. I remembered there were some difficulties implementing the beam search algorithm, so I sticked to greedy decoding at the end of the day.

**Comment by wenhuchen** [comment]
Fixed, the code somehow was deleted. Ping me if you have any further questions.
