### ISSUE TITLE
issues about decode texts

### ISSUE THREAD

**Issue by SkipAngel** [wenhuchen/KGPT#7]
bash scripts/webnlg/eval_sequence_webnlg.sh 0 challenge checkpoint_webnlg/checkpoint_finetune_sequence_head8_layer6_GPT2_maxfact12/model_ep20.pt   We didn't change the code.  File "/home/xushoukai/KGPT-webnlg/code/Model.py", line 113, in get_hypothesis
    hyp.append(self.next_ys[j+1][k])
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by wenhuchen** [comment]
Please use the same version of Pytorch.

**Comment by ilyalasy** [comment]
@SkipAngel look at the issue #6
