### ISSUE TITLE
change beam_size then everything decode as "!"

### ISSUE THREAD

**Issue by zengjia121** [wenhuchen/KGPT#9]
When I use 
"bash scripts/webnlg/eval_sequence_webnlg.sh 0 test checkpoint_webnlg/checkpoint_finetune_sequence_head8_layer6_GPT2_maxfact12_from_ep14/model_ep30.pt"
to reproduce the results ,and I find when I set beam_size >1 (using beam_search),then every word decode as "!",but when I used beam_size = 1 (using greedy_decode), it's back to normal.
I want to know how I should use beam_ Search for decoding
![图片](https://github.com/wenhuchen/KGPT/assets/73595587/77814c91-a98d-4471-907b-73afe23aec83)

**Comment by wenhuchen** [comment]
Hi, it has been too long since I released the code. I assume lots of library has updated, which led to the problem. It would be great if you could use the same old version of transformer, etc.
